### ISSUE TITLE
password hash cannot be read from environment

### ISSUE THREAD

**Issue by fnordian** [hivemq/hivemq-file-rbac-extension#11]
Hi,

I try to pass a user's password hash in from an environment variable. Unfortunately this doesn't work - authentication fails. If I place the same hash inside the xml directly it works. 

Is that supposed to work?

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<file-rbac>
    <users>
        <user>
            <name>client</name>
            <password>${ENV:PASSWORD_HASH}</password>
            <roles>
                <id>role</id>
            </roles>
        </user>
    </users>
...
```

**Comment by mhofsche** [comment]
Hi sorry for the late answer. This is not supported.
