### ISSUE TITLE
custom file path for credentials.xml and extension-config.xml

### ISSUE THREAD

**Issue by sonix07** [hivemq/hivemq-file-rbac-extension#3]
**Use Case**: updating credentials.xml with docker
It would be helpful to have the ability to set a custom file path (e.g. environment variable, having them in a sub folder would work as well) for the credentials.xml and extensions-config.xml for better docker compatibility.

**Current Behavior**: at the moment the two `.xml` files reside in the same folder as the `.jar` file itself, therefore using docker with an entire folder mapped to `/opt/hivemq/extensions/hivemq-file-rbac-extension` would overwrite the contents of the folder including the  `hivemq-file-rbac-extensionXXX.jar` causing the extension not to be loaded.
Mapping the two files explicitly from the host inside the container `/path/on/host/credentials.xml:/opt/hivemq/extensions/hivemq-file-rbac-extension/credentials.xml` and `/path/on/host/extension-config.xml:/opt/hivemq/extensions/hivemq-file-rbac-extension/extension-config.xml` works fine until the `credentials.xml` is modified (e.g. adding or changing a role) due to this issue: https://github.com/moby/moby/issues/15793#issuecomment-135411504
The result is a changed file on the host and the file inside the container still being the previous version. Restarting the container will cause the new file to be loaded, however restarting hivemq for adding and removing credentials is highly inconvenient. 

**Desired Behavior**: The ability to change the path where the config files are located to enable the possibility to use folder mounts. With folder mounts the config files changed on the host also change inside the container.

**Comment by fraschbi** [comment]
Hi  @sonix07 ,
Thank you for providing such well structured information. 
We agree that this is a reasonable and sensible request.
We will keep this issue open, as a way to track this open feature request.
In the meanwhile, may I suggest using this work around taken from the bug report you quoted.

> If you are using some editor like vim, when you save the file it does not save the file directly, rather it creates a new file and copies it into place.
> This breaks the bind-mount, which is based on inode. Since saving the file effectively changes the inode, changes will not propagate into the container.
> When the container is restarted the new inode.
> If you edit the file in place you should see changes propagate.
> 
> This is a known limitation of file-mounts and is not fixable.

Kind regards,
Florian

**Comment by sandergarretsen** [comment]
Running into the same issue. Not sure about the `extension-config.xml`. But for the `credentials.xml` it would be convenient to have the location to be configurable. Maybe inside the `extension-configration.xml`? or as an ENV var?

Just to share another workaround for the file-mount issue:
In my custom image which includes this extension, I changed the `credentials.xml` to be a symbolic link to a mounted location;
`credentials.xml -> /var/mounts/file-rbac-config/credentials.xml`
which seems to work just fine.

**Comment by chinnu0209** [comment]
Hello @sandergarretsen @fraschbi , Currently i am trying to deploy community-broker on k8s but i am facing the same issue with now i dont want to put this credentials.xml inside my pod . so that i have extension folder inside jar, extension-config include id, version.. but when mount credentials that are overwritting the files present inside extension folder that comes with private docker image. My goal is can i mount the credentials.xml during the runtime of the container and i followed your suggestion but still i can see the credentials at this location "/var/mounts/file-rbac-config/credentials.xml". If i miss anything wrong, please guide me how to solve this issue. I would like to hear from you soon. Thanks..
