### ISSUE TITLE
[BUG] 4.6.1 doesn't seem to work while 4.5.3 works.

### ISSUE THREAD

**Issue by cocoonkid** [hivemq/hivemq-file-rbac-extension#40]
![image](https://github.com/hivemq/hivemq-file-rbac-extension/assets/43231640/d2cc8d9f-ac66-49f8-b837-c7574665247c)

what could the issue be ?

EDIT:

![image](https://github.com/hivemq/hivemq-file-rbac-extension/assets/43231640/cf9492f5-4d78-4432-86a7-8bb5ebf3f05c)
4.6.0 worked immediately.

**Comment by SgtSilvio** [comment]
Hi @cocoonkid 
the issue was fixed in version 4.6.2
