### ISSUE TITLE
can this plugin be used on hivemq3.4.4 version?

### ISSUE THREAD

**Issue by taigege** [hivemq/hivemq-file-rbac-extension#8]
Excuse me, can this plugin be used on hivemq3.4.4 version?

**Comment by SgtSilvio** [comment]
Hi @taigege 
This extension can only be used with HiveMQ 4 (which is recommended to be used over HiveMQ 3).
However, the same functionality exists for HiveMQ 3 with the following plugin: https://github.com/hivemq/file-auth-plugin
For further questions, please ask them in the HiveMQ community forum: https://community.hivemq.com/
